version: '3.7'
services:
  ghostfolio:
    build: ../

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'

volumes:
  postgres:
